spring.application.name=Dream home
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/homeapp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : création auto des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
